all_tests=(
    (1, '1A Common Lab - Biochemistry', 'Serum Electrolytes / Sodium (Na)', '135 - 145 mEq/L'),
    (2, '1A Common Lab - Biochemistry', 'Serum Electrolytes / Potassium (K)', '3.8 - 5.5 mEq/L'),
    (3, '1A Common Lab - Biochemistry', 'Serum Electrolytes / Chloride (Cl)', '100-108 mEq/L'),
    (4, '1A Common Lab - Biochemistry', 'Serum Electrolytes / Bicarbonate (HCO3)', '22-26 mEq/L'),
    (5, '1A Common Lab - Biochemistry', 'Serum Electrolytes / Calcium (Ca) Total', '8.5-10.5 mg/dL'),
    (6, '1A Common Lab - Biochemistry', 'Serum Electrolytes / Calcium (Ca) Ionized', '4.6-5.3 mg/dL'),
    (7, '1A Common Lab - Biochemistry', 'Serum Electrolytes / Phosphate', '2.6-4.5 mg/dL'),
    (8, '1A Common Lab - Biochemistry', 'Serum Electrolytes / Magnesium (Mg)', '1.4-2.0 mEq/L'),
    (9, '1A Common Lab - Biochemistry', 'Serum Electrolytes / Anion Gap (Na-(Cl+HCO3))', '7-14 mEq/L'),
    (10, '1A Common Lab - Biochemistry', 'Serum Electrolytes / Osmolilty', '280-296 mmol/Kg H2O'),
    (11, '1A Common Lab - Biochemistry', 'Serum Non-Electrolytes / / BUN (Blood Urea Nitrogen)', '8 - 25 mg/dL'),
    (12, '1A Common Lab - Biochemistry', 'Serum Non-Electrolytes / Creatinine', '70 - 150 micromol/L (relative to BMI)'),
    (13, '1A Common Lab - Biochemistry', 'Random Blood Glucose Level', '<11 mmol/L'),
    (16, '1A Common Lab - Biochemistry', 'Fasting Blood Glucose Level', 'Pre test value: < 6.0 mmol/L (>6.0 - < 7.0 mmol/L suggests impaired fasting glycemia) 2 hr post test value: < 11.1 mmol/L (>7.8 mmol/L - <11.0 mmol/L suggests impaired Glucose tolerance)'),
    (17, '1A Common Lab - Biochemistry', 'Serum Non-Electrolytes / Glucose (2 hr post prandial)', '< 7.8 mmol/L'),
    (18, '1A Common Lab - Biochemistry', 'Serum Non-Electrolytes / Uric Acid', '210-500 micromol/L (M), 140-400 micromol/L (F)'),
    (19, '1A Common Lab - Biochemistry', 'Serum Non-Electrolytes / Lactate', '1 - 2 mmol/L'),
    (20, '1A Common Lab - Biochemistry', 'Serum Non-Electrolytes / Salicylate', 'therapeutic levels: < 20 mg/dL for analgesia, < 50 mg/dL for anti-inflammatory.? Toxic levels: mild 50-80 mg/dL, severe 80-110 mg/dL'),
    (21, '1A Common Lab - Biochemistry', 'Serum Non-Electrolytes / Ethanol', 'inebriation 80-150 mg/dL, loss of muscle coordination 150-200 mg/dL, decreased LOC 200-300 mg/dL, coma and death 300-500 mg/dL (estimations - may be higher in alcoholics)'),
    (22, '1A Common Lab - Biochemistry', 'Serum Non-Electrolytes / Methanol', 'Absent'),
    (23, '1A Common Lab - Biochemistry', 'Serum Non-Electrolytes / Ethylene Glycol', 'Absent'),
    (24, '1A Common Lab - Biochemistry', 'Serum Non-Electrolytes / Paraldehyde', 'Absent'),
    (25, '1A Common Lab - Biochemistry', 'Serum Liver Pancreatic Tests / Albumin', '31-43 g/L'),
    (26, '1A Common Lab - Biochemistry', 'Serum Liver Pancreatic Tests / Lipase', '10-140 U/L'),
    (27, '1A Common Lab - Biochemistry', 'Serum Liver Pancreatic Tests / Amylase', '53-123 U/L'),
    (28, '1A Common Lab - Biochemistry', 'Serum Liver Pancreatic Tests / Alanine Aminotransferase (ALT)', '8-20 U/L'),
    (29, '1A Common Lab - Biochemistry', 'Serum Liver Pancreatic Tests / Aspartate Aminotransferase (AST)', '10-30 U/L'),
    (30, '1A Common Lab - Biochemistry', 'Serum Liver Pancreatic Tests / Glutamyltransferase (GGT)', '1-94 U/L (M), 1-70 U/L (F)'),
    (31, '1A Common Lab - Biochemistry', 'Serum Liver Pancreatic Tests / Alkaline Phosphatase (ALP)', '45 - 115 U/L (M), 30-100 U/L (F)'),
    (32, '1A Common Lab - Biochemistry', 'Serum Liver Pancreatic Tests / Bilirubin (direct)', '0-7 micromol/L'),
    (33, '1A Common Lab - Biochemistry', 'Serum Liver Pancreatic Tests / Total Bilirubin', '0-17 micromol/L'),
    (34, '1A Common Lab - Biochemistry', 'Troponin T/ Troponin I?', 'Negative - may increase to > 20 times upper limit of normal (rise 4-6 hr post-injury. Do serial troponin levels)'),
    (35, '1A Common Lab - Biochemistry', 'HbA1C', '<7% (3.8-6.4%)'),
    (36, '1A Common Lab - Biochemistry', 'Serum Lead', 'Normal'),
    (37, '1A Common Lab - Hematology', 'Hemoglobin (Hg)', '130-180 g/L (M), 120-160 g/L (F)'),
    (38, '1A Common Lab - Hematology', 'Hematocrit (Hct)', '0.37-0.49 (M), 0.36-0.46 (F)'),
    (39, '1A Common Lab - Hematology', 'Mean Corpuscular Hb Concentration (MCHC)', '310-370 g/L'),
    (40, '1A Common Lab - Hematology', 'Mean Corpuscular Volume (MCV)', '78-100 fL'),
    (41, '1A Common Lab - Hematology', 'Erythrocyte count', '4.5-5.3 X10E12/L (M), 4.10-5.10 X 10E12/L (F)'),
    (42, '1A Common Lab - Hematology', 'WBC (total)', '4.5-11.0 X 10E9 /L'),
    (43, '1A Common Lab - Hematology', 'WBC- Neutrophils Segmented', '45 - 65%'),
    (44, '1A Common Lab - Hematology', 'WBC-Neutrophils Bands', '3 - 5%'),
    (48, '1A Common Lab - Hematology', 'Platelets (Plt)', '150 - 400 X 10E9 / L'),
    (49, '1A Common Lab - Hematology', 'Coagulation Activated Partial Thromboplastin Time (aPTT)', '22.1-34.1 s'),
    (50, '1A Common Lab - Hematology', 'Coagulation aPTT with Therapeutic IV Heparin', '60-85 s'),
    (51, '1A Common Lab - Hematology', 'Coagulation Bleeding Time', '2.0-9.5 min'),
    (52, '1A Common Lab - Hematology', 'Coagulation Internationalized Normalized Ratio (INR)', '1.0-1.1'),
    (53, '1A Common Lab - Hematology', 'Erythrocyte Sedimentation Rate (ESR)', '0-20 mm/hr'),
    (54, '1A Common Lab - Hematology', 'Reticulocytes', 'Adults: 0.5-2.5% red cells; Children: 2.5-6.5% red cells'),
    (55, '1A Common Lab - Hematology', 'WBC-Bone Marrow', '3-21%'),
(58, '1A Common Lab - Hematology', 'Serum Copper', 'Negative'),
(59, '1A Common Lab - Hematology', 'Sickle Cell Screen', 'Negative'),
(60, '1A Common Lab - Hematology', 'Hemoglobin Electrophoresis', 'Negative'),
(62, '1A Common Lab - Endocrinology', 'Aldosterone', '0.06-0.7 nmol/L (supine), 2-5 times supine value if upright'),
(63, '1A Common Lab - Endocrinology', 'B - HCG', 'undetectable'),
(64, '1A Common Lab - Endocrinology', 'Calcitonin', '3-26 ng/L (M), 2-17 ng/L (F)'),
(65, '1A Common Lab - Endocrinology', 'Cortisol', '138-690 nmol/L (0800 hr) ; 138-414 nmol/L (1600 hr)'),
(66, '1A Common Lab - Endocrinology', 'C-peptide', '0.26-0.62 nmol/L'),
(67, '1A Common Lab - Endocrinology', 'Dehydroepiandosterone Sulfate (DHEA-S)', '100-6190 ug/L (M) ; 120-5350 ug/L (female)'),
(68, '1A Common Lab - Endocrinology', 'Estradiol', 'male < 184 pmol/L? ; menstruating female:184-532 pmol/L (follicular phase), 411-1626 pmol/L (ovulatory peak) ; 184-885 pmol/L (luteal phase) ; postmenopausal female < 217 pmol/L?'),
(69, '1A Common Lab - Endocrinology', 'Follicle Stimulating Hormone', ''),
(70, '1A Common Lab - Endocrinology', 'Growth Hormone', '2-5 ug/L'),
(71, '1A Common Lab - Endocrinology', 'Luteinizing Hormone', ''),
(72, '1A Common Lab - Endocrinology', 'Progesterone', ''),
(73, '1A Common Lab - Endocrinology', 'Prolactin', ''),
(74, '1A Common Lab - Endocrinology', 'Parathyroid Hormone (PTH)', '10-65 ng/L'),
(75, '1A Common Lab - Endocrinology', 'Serotonin (5-HT)', '0.31-1.48 umol/L'),
(76, '1A Common Lab - Endocrinology', 'Testosterone', ''),
(77, '1A Common Lab - Endocrinology', 'Thyroid Stimulating Hormone (TSH)', '0.5-5.0 mU/L'),
(78, '1A Common Lab - Endocrinology', 'Thyroxine (T4)', 'Free: 10-31 pmol/L ; Total: 58-140 nmol/L'),
(79, '1A Common Lab - Endocrinology', 'Triiodothyronine (T3)', '0.92-2.78 nmol/L'),
(80, '1A Common Lab - Endocrinology', 'Vasoactive Intestinal Polypeptide (VIP)', '< 75 ng/L'),
(81, '1A Common Lab - Immunology', 'Skin Prick Test', 'Negative'),
(84, '1B Urine Test - Biochemistry', 'Urinalysis / pH', '5.0-9.0'),
(85, '1B Urine Test - Biochemistry', 'Urinalysis / Specific Gravity', '1.001-1.035'),
(86, '1B Urine Test - Biochemistry', 'Urinalysis / Minimum Volume', '0.5-1.0 mL/kg/h'),
(87, '1B Urine Test - Biochemistry', 'Urinalysis / Osmolality', '50-1400 mOsm/kg'),
(88, '1B Urine Test - Biochemistry', 'Urinalysis / Creatinine', '15-25 mg/kg/day'),
(89, '1B Urine Test - Biochemistry', 'Urinalysis / Creatinine clearance', '1.5-2.3 mL/sec/1.73 meter squared (M) ; 1.3-2.1 mL/sec/1.73 meter squared (F)'),
(90, '1B Urine Test - Biochemistry', 'Urinalysis / Urea Nitrogen', '210-600 mmol/day'),
(91, '1B Urine Test - Biochemistry', 'Urinalysis / Sodium', '40-220 mmol/day'),
(92, '1B Urine Test - Biochemistry', 'Urinalysis / Potassium', '25-125 mmol/day'),
(93, '1B Urine Test - Biochemistry', 'Urinalysis / Calcium', '2.5-7.5 mmol/day'),
(94, '1B Urine Test - Biochemistry', 'Urinalysis / Phosphate', '13-42 mmol/day'),
(95, '1B Urine Test - Biochemistry', 'Urinalysis / Uric Acid', '1.48-4.43 mmol/day'),
(96, '1B Urine Test - Biochemistry', 'Urinalysis / Glucose', '<0.003 mmol/day'),
(97, '1B Urine Test - Biochemistry', 'Urinalysis / Albumin', '0.01-00.10 g/day'),
(98, '1B Urine Test - Biochemistry', 'Urinalysis / Protein', '0.01-0.15 g/day'),
(99, '1B Urine Test - Biochemistry', 'Urinalysis / Sediment - White Cells', '0-2 / high power field'),
(100, '1B Urine Test - Biochemistry', 'Urinalysis / Sediment - Red Cells', '0-2 / high power field'),
(101, '1B Urine Test - Biochemistry', 'Urinalysis / Ketones', 'Negative'),
(102, '1B Urine Test - Biochemistry', 'Urinalysis / Nitrites', 'Negative'),
(103, '1B Urine Test - Biochemistry', 'Urinalysis / Leukocyte Esterase', 'Negative'),
(104, '1B Urine Test - Biochemistry', 'Urinary Metabolites / Vanillylmandelic Acid (VMA) 24 hr', 'Negative'),
(105, '1B Urine Test - Biochemistry', 'Urinary Catecholamines / Dopamine', '340-3134 nmol/day'),
(106, '1B Urine Test - Biochemistry', 'Urinary Catecholamines / Epinephrine', '11-131 nmol/day'),
(107, '1B Urine Test - Biochemistry', 'Urinary Catecholamines / Norepinephrine', '89-591 nmol/day'),
(108, '1B Urine Test - Biochemistry', 'Urinary Catecholamines / Total (Epinephrine + Norepinephrine)', '142-660 nmol/day'),
(109, '1C Microbiology - Bacteriology', 'Stool Cultures', 'Negative'),
(110, '1C Microbiology - Virology/Serology', 'Mono Screen', 'Negative'),
(111, '1C Microbiology - Virology/Serology', 'Rubella Screen', 'Negative'),
(112, '1C Microbiology - Virology/Serology', 'Cold Agglut', '<1:32'),
(113, '1C Microbiology - Virology/Serology', 'Streptococcal Bacteria', 'Absent'),
(114, '1C Microbiology - Virology/Serology', 'Throat Swab', 'Healthy'),
(115, '1C Microbiology - Virology/Serology', 'Hepatitis A', 'Negative'),
(116, '1C Microbiology - Virology/Serology', 'HIV', 'Negative'),
(117, '1C Microbiology - Virology/Serology', 'Sputum Culture', 'No bacterial found'),
(118, '1D Cerebral Spinal Fluid (CSF)', 'albumin', '0.11-0.48 g/L'),
(119, '1D Cerebral Spinal Fluid (CSF)', 'Cell count', '0-5 cells/uL'),
(120, '1D Cerebral Spinal Fluid (CSF)', 'Chloride', '120-130 mmol/L'),
(121, '1D Cerebral Spinal Fluid (CSF)', 'Glucose?', '2.8-4.2 mmol/L'),
(122, '1D Cerebral Spinal Fluid (CSF)', 'Opening pressure', '70-180 mm Hg'),
(123, '1D Cerebral Spinal Fluid (CSF)', 'IgG', '0.08-0.086 g/L'),
(124, '1D Cerebral Spinal Fluid (CSF)', 'Protein (lumbar)', '0.15-0.45 g/L'),
(125, '2A Nuclear Medicine', 'Radionuclide Scan of Thyroid Gland', 'Normal'),
(126, '2B Radiology', 'Chest X - Ray', 'No bone, heart, or lung abnormalities seen.'),
(127, '2B Radiology', 'CT / Head', 'Normal'),
(129, '2B Radiology', 'Digestive tract / Oral Cholecystogram (OCG)', 'No gallstones'),
(130, '2B Radiology', 'Echocardiography / Echocardiogram', 'Left ventricular ejection fraction of > 55% No inspiratory collapse of the right ventricle Normal function of the mitral and aortic valves. Normal aortic root..Normal aortic"'),
(131, '2B Radiology', 'Extremities / Shoulder X - Ray', 'Normal muscle tone'),
(132, '2B Radiology', 'Ultrasound / Abdominal Scan', 'Normal biliary tree and gallbladder. No hepatic lesions. Normal abdominal aorta, pancreas, spleen and kidneys. Retroperitoneal space obscured by bowel gas.'),
(133, '4A Respiratory Service - Pulmonary function tests', 'Spirometry', 'Normal'),
(134, '4A Respiratory Service - Pulmonary function tests', 'Peak Expiratory Flow Rate (PEFR)', 'Normal'),
(135, '4B Electrocardiogram (ECG)', 'Plain ECG', 'Normal'),
(136, '4B Electrocardiogram (ECG)', 'ECG with exercise', 'Normal'),
(137, '4B Electrocardiogram (ECG)', 'Continual ECG Monitoring', 'Normal'),
(138, '4B Electrocardiogram (ECG)', 'ECG exercise stress test', 'Normal'),
(139, '4C Electroencephalogram (EEG)', 'EEG', 'Normal'),
(140, '4E Arterial Blood Gases (ABG)', 'pH', '7.35-7.45'),
(141, '4E Arterial Blood Gases (ABG)', 'pCO2', '35-45 mm Hg'),
(142, '4E Arterial Blood Gases (ABG)', 'pO2', '80-100 mm Hg'),
(143, '4E Arterial Blood Gases (ABG)', 'SaO2', '95-98%'),
(144, '4F Lipoprotein Electrophoresis', 'Lipoprotein Electrophoresis', 'Negative'),
(145, '5 Biopsy', 'Muscle biopsy', 'Normal'),
(146, '5 Biopsy', 'Lung biopsy', 'Normal'),
(147, '6 Genetic Tests', 'Gene-Huntingtons', 'Negative'),
(148, '6 Genetic Tests', 'Karyotyping', 'Normal'),
(149, '7 Extra Physical Examinations', 'Eye Exam', 'Normal'),
(150, '1A Common Lab - Biochemistry', 'Serum Ketones', 'Absent'),
(151, '1B Urine Test - Biochemistry', 'Urinary Catecholamines / Free', 'tba'),
(155, '1A Common Lab - Immunology', 'Thyroid Stimulating Immunoglobulin Assay', 'Normal'),
(156, '8 Toxicology Screening', 'Ethanol', 'Absent'),
(157, '8 Toxicology Screening', 'Tylenol', 'Absent'),
(158, '8 Toxicology Screening', 'Methanol', 'Absent'),
(159, '8 Toxicology Screening', 'Barbiturates', 'Absent'),
(160, '8 Toxicology Screening', 'Ethylene Glycol', 'Absent'),
(161, '8 Toxicology Screening', 'Tricyclic antidepressants', 'Absent'),
(163, '1C Microbiology - Bacteriology', 'Fecal Occult Blood Test (FOBT)', 'Normal'),
(164, '7 Extra Physical Examinations', 'Lung exam', 'Normal'),
(167, '1A Common Lab - Hematology', 'Anti-tissue Transglutaminase Antibody (tTG)', 'Negative'),
(168, '7 Extra Physical Examinations', 'Abdominal Exam', 'Normal'),
(174, '1A Common Lab - Hematology', 'Anti-Gliadin Antibody (AGA)', 'negative'),
(197, '2B Radiology', 'CT / Chest', 'Normal'),
(198, '2B Radiology', 'CT / Abdomen', 'Normal'),
(176, '1A Common Lab - Hematology', 'Anti-Endomysial Antibody (AEA)', 'negative'),
(177, '1C Microbiology - Bacteriology', 'Stool Gram Stain', 'Negative'),
(179, '1A Common Lab - Endocrinology', 'Adrenocorticotropin hormone (ACTH)', '1.8-17.4 pmol/L (0800 hr) ; 1.5-6.6 pmol/L (1600 hr)'),
(180, '1A Common Lab - Immunology', 'IgE Levels', 'Normal range'),
(181, '1A Common Lab - Hematology', 'WBC-Eosinophils', '2 - 4%'),
(182, '1A Common Lab - Hematology', 'WBC-Lymphocytes', '20 - 40%'),
(183, '1A Common Lab - Hematology', 'WBC-Monocytes', '0 - 8%'),
(184, '7 Extra Physical Examinations', 'Skin Exam', 'Normal'),
(185, '1B Urine Test - Biochemistry', 'Urinalysis / Chloride ', '4.0-20.0 g/L'),
(186, '1B Urine Test - Biochemistry', 'Urinalysis / Bilirubin ', 'Absent'),
(187, '1C Microbiology - Parasitology ', 'Blood ', 'No parasites seen'),
(188, '1C Microbiology - Parasitology ', 'Stool ', 'No parasites seen'),
(189, '1C Microbiology - Parasitology ', 'Urine', 'No parasites seen'),
(190, '1E Peritoneal Fluid ', 'Albumin', 'Normal'),
(191, '1E Peritoneal Fluid ', 'Cell Count', 'Normal'),
(192, '1F Pleural Fluid ', 'Albumin', 'Normal'),
(193, '1F Pleural Fluid ', 'Cell Count', 'Normal'),
(194, '4G Gastroenterology Service', 'Gastroscopy', 'Normal'),
(195, '4G Gastroenterology Service', 'Colonoscopy', 'Normal'),
(196, '4G Gastroenterology Service', 'EGD with Small Bowel Biopsy', 'Normal'),
(199, '7 Extra Physical Examinations', 'Head Exam (Eyes, Ears, Nose, Throat) ', 'Normal'),
(200, '7 Extra Physical Examinations', 'Heart Exam', 'Normal'),
(201, '7 Extra Physical Examinations', 'Rectal Exam', 'Normal'),
(202, '7 Extra Physical Examinations', 'Genital Exam', 'Normal'),
(203, '7 Extra Physical Examinations', 'Musculoskeletal Exam', 'Normal'),
(204, '7 Extra Physical Examinations', 'Neurologic Exam', 'Normal'),
(205, '1A Common Lab - Immunology', 'cANCA', 'Negative'),
(206, '1A Common Lab - Immunology', 'pANCA', 'Negative'),
(207, '1A Common Lab - Immunology', 'C Reactive Protein', '0 - 5 mg/L'),
(208, '2B Radiology', 'X-ray sinuses', 'Sinuses patent without evidence of inflammation.'),
(214, '1A Common Lab - Biochemistry', 'Vitamin B12 level', '200-400 pg/L'),
(215, '1A Common Lab - Biochemistry', 'Serum Liver Pancreatic Tests / Lactate Dehydrogenase', '60-160 U/L'),
(216, '1A Common Lab - Biochemistry', 'Methylmalonic acid level', ''))

def get_medical_tests():
    tests=[t[1:] for t in all_tests]
    tests.sort()
    tests=[{"name":i[1],"category":i[0],"default":i[2]} for i in tests]
    return tests
    return (test1,test2,test3,test4,test5)


